/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackedIndexRouteImport } from './routes/tracked/index'
import { Route as DriftIndexRouteImport } from './routes/drift/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as CastIndexRouteImport } from './routes/cast/index'
import { Route as DocsTrackedRouteImport } from './routes/docs/tracked'
import { Route as DocsScoringRouteImport } from './routes/docs/scoring'
import { Route as DocsPricingRouteImport } from './routes/docs/pricing'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as DocsDriftRouteImport } from './routes/docs/drift'
import { Route as DocsCastRouteImport } from './routes/docs/cast'
import { Route as DocsApiRouteImport } from './routes/docs/api'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackedIndexRoute = TrackedIndexRouteImport.update({
  id: '/tracked/',
  path: '/tracked/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftIndexRoute = DriftIndexRouteImport.update({
  id: '/drift/',
  path: '/drift/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const CastIndexRoute = CastIndexRouteImport.update({
  id: '/cast/',
  path: '/cast/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTrackedRoute = DocsTrackedRouteImport.update({
  id: '/tracked',
  path: '/tracked',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsScoringRoute = DocsScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPricingRoute = DocsPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsDriftRoute = DocsDriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsCastRoute = DocsCastRouteImport.update({
  id: '/cast',
  path: '/cast',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/cast': typeof DocsCastRoute
  '/docs/drift': typeof DocsDriftRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/scoring': typeof DocsScoringRoute
  '/docs/tracked': typeof DocsTrackedRoute
  '/cast/': typeof CastIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/drift/': typeof DriftIndexRoute
  '/tracked/': typeof TrackedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/cast': typeof DocsCastRoute
  '/docs/drift': typeof DocsDriftRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/scoring': typeof DocsScoringRoute
  '/docs/tracked': typeof DocsTrackedRoute
  '/cast': typeof CastIndexRoute
  '/docs': typeof DocsIndexRoute
  '/drift': typeof DriftIndexRoute
  '/tracked': typeof TrackedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/cast': typeof DocsCastRoute
  '/docs/drift': typeof DocsDriftRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/pricing': typeof DocsPricingRoute
  '/docs/scoring': typeof DocsScoringRoute
  '/docs/tracked': typeof DocsTrackedRoute
  '/cast/': typeof CastIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/drift/': typeof DriftIndexRoute
  '/tracked/': typeof TrackedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/about'
    | '/changelog'
    | '/pricing'
    | '/settings'
    | '/docs/api'
    | '/docs/cast'
    | '/docs/drift'
    | '/docs/faq'
    | '/docs/getting-started'
    | '/docs/pricing'
    | '/docs/scoring'
    | '/docs/tracked'
    | '/cast/'
    | '/docs/'
    | '/drift/'
    | '/tracked/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/pricing'
    | '/settings'
    | '/docs/api'
    | '/docs/cast'
    | '/docs/drift'
    | '/docs/faq'
    | '/docs/getting-started'
    | '/docs/pricing'
    | '/docs/scoring'
    | '/docs/tracked'
    | '/cast'
    | '/docs'
    | '/drift'
    | '/tracked'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/about'
    | '/changelog'
    | '/pricing'
    | '/settings'
    | '/docs/api'
    | '/docs/cast'
    | '/docs/drift'
    | '/docs/faq'
    | '/docs/getting-started'
    | '/docs/pricing'
    | '/docs/scoring'
    | '/docs/tracked'
    | '/cast/'
    | '/docs/'
    | '/drift/'
    | '/tracked/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  CastIndexRoute: typeof CastIndexRoute
  DriftIndexRoute: typeof DriftIndexRoute
  TrackedIndexRoute: typeof TrackedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracked/': {
      id: '/tracked/'
      path: '/tracked'
      fullPath: '/tracked/'
      preLoaderRoute: typeof TrackedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift/': {
      id: '/drift/'
      path: '/drift'
      fullPath: '/drift/'
      preLoaderRoute: typeof DriftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/cast/': {
      id: '/cast/'
      path: '/cast'
      fullPath: '/cast/'
      preLoaderRoute: typeof CastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tracked': {
      id: '/docs/tracked'
      path: '/tracked'
      fullPath: '/docs/tracked'
      preLoaderRoute: typeof DocsTrackedRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/scoring': {
      id: '/docs/scoring'
      path: '/scoring'
      fullPath: '/docs/scoring'
      preLoaderRoute: typeof DocsScoringRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pricing': {
      id: '/docs/pricing'
      path: '/pricing'
      fullPath: '/docs/pricing'
      preLoaderRoute: typeof DocsPricingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/drift': {
      id: '/docs/drift'
      path: '/drift'
      fullPath: '/docs/drift'
      preLoaderRoute: typeof DocsDriftRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/cast': {
      id: '/docs/cast'
      path: '/cast'
      fullPath: '/docs/cast'
      preLoaderRoute: typeof DocsCastRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsCastRoute: typeof DocsCastRoute
  DocsDriftRoute: typeof DocsDriftRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsPricingRoute: typeof DocsPricingRoute
  DocsScoringRoute: typeof DocsScoringRoute
  DocsTrackedRoute: typeof DocsTrackedRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsCastRoute: DocsCastRoute,
  DocsDriftRoute: DocsDriftRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsPricingRoute: DocsPricingRoute,
  DocsScoringRoute: DocsScoringRoute,
  DocsTrackedRoute: DocsTrackedRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  CastIndexRoute: CastIndexRoute,
  DriftIndexRoute: DriftIndexRoute,
  TrackedIndexRoute: TrackedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
